package com.ifpe.pw_defesa_civil.model.enums;

public enum TipoProcesso {
    VISTORIA,
    VISTORIA_BARRAGEM,
    VISTORIA_MORRO,
    VISTORIA_EDIFICIO,
    MONITORAMENTO,
    MAPEAMENTO_DESLIZAMENTO,
    MAPEAMENTO_INUNDACAO,
    MAPEAMENTO_BARRAGEM,
    MAPEAMENTO_EROSAO,
    MAPEAMENTO_INFRAESTRUTURA,
    VISITA_TECNICA
    ;
}
